version: '3.8'

services:
  vectorizer-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend_processor/uploads:/app/backend_processor/uploads
      - ./backend_processor/outputs:/app/backend_processor/outputs
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
